version: '2'

volumes:
  nextcloud:
  data: {}
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= # Add a root password
      - MYSQL_PASSWORD= # Add mysql password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD= # Add mysql password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS= # Add your desired domain
    depends_on:
      - db
      - redis

  web:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - nextcloud:/var/www/html
    depends_on:
      - app

  redis:
    image: redis:alpine
    restart: always


